### ISSUE TITLE
Can't install prebuilt via npm

### ISSUE THREAD

**Issue by vzamanillo** [Ivshti/wcjs-prebuilt#29]
**cmd**: `npm install wcjs-prebuilt --save-dev`

Tested on
- node 6.3.0
- node 6.0.0
- node 5.0.0
- node 4.1.0

``` bash
> wcjs-prebuilt@3.0.0 postinstall C:\desarrollo\GitWorkspace\desktop\src\node_modules\wcjs-prebuilt
> node install.js

parse-filepath expects a string.
Error: parse-filepath expects a string.
    at parse (C:\desarrollo\GitWorkspace\desktop\src\node_modules\parse-filepath\index.js:11:11)
    at C:\desarrollo\GitWorkspace\desktop\src\node_modules\wcjs-prebuilt\install.js:112:17
    at tryCatcher (C:\desarrollo\GitWorkspace\desktop\src\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._resolveFromResolver (C:\desarrollo\GitWorkspace\desktop\src\node_modules\bluebird\js\main\promise.js:480:31)
    at new Promise (C:\desarrollo\GitWorkspace\desktop\src\node_modules\bluebird\js\main\promise.js:70:37)
    at parseEnv (C:\desarrollo\GitWorkspace\desktop\src\node_modules\wcjs-prebuilt\install.js:91:12)
    at Object.<anonymous> (C:\desarrollo\GitWorkspace\desktop\src\node_modules\wcjs-prebuilt\install.js:149:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "wcjs-prebuilt" "--save-dev"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! wcjs-prebuilt@3.0.0 postinstall: `node install.js`
```

**Comment by Kiblyn11** [comment]
Its because there is no main entry in your package.json file.
You can fix it by yourself by adding to your package.json file `"main": ""`

I added a PR to manage if there is no main entry. #30

**Comment by vzamanillo** [comment]
Thank you very much!!

**Comment by vzamanillo** [comment]
In my case the problem was other, my project root has a simple manifest `./package.json`  with development dependencies for building the package app only, but the real manifest is located into a subfolder `./src/package.json` with all application details and from where all application dependencies are resolved, I am trying to install the prebuilt via`npm install wcjs-prebuilt --save-dev` from that folder but

`var findProjectRoot = require('find-project-root');`

returns the project base path '.' so the main manifest entry (in `./src/package.json`) is not resolved, should be the main manifest entry resolved from the current process directory?

**Comment by 13protons** [comment]
@vzamanillo A little poking around here shows that the `find-project-root` package defaults to nvm's package.json for my node version (4.4.7) installed with node version manager.

**Comment by erikyuzwa** [comment]
just confirming here that I also needed to add a `"main":""` in the `package.json` of my project root in my electron app for this to successfully install even though my `app` subfolder is where I'm running `npm` from.

**Comment by leandronn** [comment]
Same happens in ubuntu 16.04

`leandro@LNN-ENVY:/var/www/public_html/butterproject$ npm install wcjs-prebuilt --save-dev

> wcjs-prebuilt@2.1.0 postinstall /var/www/public_html/butterproject/node_modules/wcjs-prebuilt
> node install.js

Runtime detected as: electron 
Arch: x64
Acquiring:  undefined
undefined is not a valid uri or options object.
Error: undefined is not a valid uri or options object.
    at request (/var/www/public_html/butterproject/node_modules/request/index.js:46:11)
    at Object.module.exports.downloadAndUnpack (/var/www/public_html/butterproject/node_modules/wcjs-prebuilt/lib/downloader.js:29:18)
    at /var/www/public_html/butterproject/node_modules/wcjs-prebuilt/install.js:54:28
    at tryCatcher (/var/www/public_html/butterproject/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/var/www/public_html/butterproject/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/var/www/public_html/butterproject/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/var/www/public_html/butterproject/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/var/www/public_html/butterproject/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/var/www/public_html/butterproject/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/public_html/butterproject/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "wcjs-prebuilt" "--save-dev"
npm ERR! node v4.2.6
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! wcjs-prebuilt@2.1.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wcjs-prebuilt@2.1.0 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wcjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wcjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wcjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/public_html/butterproject/npm-debug.log
`

**Comment by leandronn** [comment]
Same happens in Ubuntu 16.04

```
leandro@LNN-ENVY:/var/www/public_html/butterproject$ npm install wcjs-prebuilt --save-dev

 wcjs-prebuilt@2.1.0 postinstall /var/www/public_html/butterproject/node_modules/wcjs-prebuilt
node install.js

Runtime detected as: electron 
Arch: x64
Acquiring:  undefined
undefined is not a valid uri or options object.
Error: undefined is not a valid uri or options object.
    at request (/var/www/public_html/butterproject/node_modules/request/index.js:46:11)
    at Object.module.exports.downloadAndUnpack (/var/www/public_html/butterproject/node_modules/wcjs-prebuilt/lib/downloader.js:29:18)
    at /var/www/public_html/butterproject/node_modules/wcjs-prebuilt/install.js:54:28
    at tryCatcher (/var/www/public_html/butterproject/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/var/www/public_html/butterproject/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/var/www/public_html/butterproject/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/var/www/public_html/butterproject/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/var/www/public_html/butterproject/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/var/www/public_html/butterproject/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/public_html/butterproject/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "wcjs-prebuilt" "--save-dev"
npm ERR! node v4.2.6
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! wcjs-prebuilt@2.1.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wcjs-prebuilt@2.1.0 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wcjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wcjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wcjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/public_html/butterproject/npm-debug.log

```

**Comment by erikyuzwa** [comment]
@leandronn - have you tried rolling back `npm`? 

```
npm -v
2.15.9
node -v
v4.6.0
```

Is what I've been using on the Windows side without any issues.

**Comment by leandronn** [comment]
@erikyuzwa Hi, thanks for answering.
Im using

```
npm -v
3.10.8

node -v
v4.2.6

```

Should I downgrade just npm?

**Comment by erikyuzwa** [comment]
perhaps try that first, yeah. We're on the same major version of node, so hopefully that's sufficient.

**Comment by leandronn** [comment]
@erikyuzwa same as before

```
npm ERR! node v4.2.6
npm ERR! npm  v2.15.9

```

**Comment by erikyuzwa** [comment]
silly question, but do you have the `wcjs-prebuilt` key defined in your root `./package.json`?
mine is

```
"wcjs-prebuilt": {
  "arch": "x64",
  "runtime": "electron",
  "runtimeVersion": "v1.3.5",
  "version": "v0.2.6"
}
```

**Comment by erikyuzwa** [comment]
where `runtimeVersion` is the version of Electron you're using and `version` is the version of `wcjs-prebuilt` you want.

**Comment by leandronn** [comment]
@erikyuzwa was not that silly. Only the version was defined. Now it works, thanks a lot for your time.

**Comment by erikyuzwa** [comment]
most excellent @leandronn! 🙇
