### ISSUE TITLE
WebChimera.js.node - Module parse failed

### ISSUE THREAD

**Issue by hadees** [Ivshti/wcjs-prebuilt#33]
I've been trying to get WebChimera prebuilts to load and I keep getting parsing errors for the file `WebChimera.js.node`

```
         ERROR in ./~/webchimera.js/WebChimera.js.node
         Module parse failed: /Users/gremlin/code/flip/node_modules/webchimera.js/WebChimera.js.node Unexpected character '�' (1:0)
         You may need an appropriate loader to handle this file type.
         SyntaxError: Unexpected character '�' (1:0)
             at Parser.pp$4.raise (/Users/gremlin/code/flip/node_modules/acorn/dist/acorn.js:2221:15)
             at Parser.pp$7.getTokenFromCode (/Users/gremlin/code/flip/node_modules/acorn/dist/acorn.js:2756:10)
             at Parser.pp$7.readToken (/Users/gremlin/code/flip/node_modules/acorn/dist/acorn.js:2477:17)
             at Parser.pp$7.nextToken (/Users/gremlin/code/flip/node_modules/acorn/dist/acorn.js:2468:15)
             at Parser.parse (/Users/gremlin/code/flip/node_modules/acorn/dist/acorn.js:515:10)
             at Object.parse (/Users/gremlin/code/flip/node_modules/acorn/dist/acorn.js:3098:39)
             at Parser.parse (/Users/gremlin/code/flip/node_modules/webpack/lib/Parser.js:902:15)
             a
```

Is there some sort of configuration I'm missing when using `const Wjs = require('wcjs-player')`?  I'm using `"wcjs-player": "^6.0.1"` in `"electron-prebuilt": "1.3.1"`.  I know the latest version of `electron` had some problems with `WebChimera.js`.

**Comment by Ivshti** [comment]
Yes, it has to be compiled to your current CPU architecture and OS. Is it?

**Comment by hadees** [comment]
@Ivshti this I think actually turned out to be a [Webkit issue](https://github.com/RSATom/WebChimera.js/wiki/WebChimera.js-with-Webpack).
